#!/usr/bin/env ruby
puts $stdin.readlines.count { |line|
  /^(?<min>\d+)-(?<max>\d+) (?<c>.): (?<password>.*)$/ =~ line
  count = password.chars.count { |char| c == char }
  min.to_i <= count && count <= max.to_i
}
