#!/usr/bin/env ruby

cutoff = 10_000

def self.in_region?(x, y, points, cutoff)
  distance = 0
  points.each do |px, py|
    distance += (x-px).abs
    distance += (y-py).abs
    break if distance > cutoff
  end
  distance < cutoff
end

points = $stdin.read.scan(/\d+/).map(&:to_i).each_slice(2).to_a
width, height = points.transpose.map(&:max).map(&:succ)

count = height.times.sum do |y|
  width.times.count do |x|
    in_region? x, y, points, cutoff
  end
end

p count
