#!/usr/bin/env ruby -n

BEGIN {
  squares = Hash.new { |h, k| h[k] = [] }
  ids = {}
}

id, x, y, w, h = $_.scan(/\d+/).map(&:to_i)
ids[id] = false
x.upto(x+w-1) do |crnt_x|
  y.upto(y+h-1) { |crnt_y| squares[[crnt_x, crnt_y]] << id }
end

END {
  squares.each do |_, xy_ids|
    next if xy_ids.size < 2
    xy_ids.each { |id| ids[id] = true }
  end
  ids.each { |id, overlaps| puts id unless overlaps }
}
