#!/usr/bin/env ruby
score = 0

ARGF.each do |line|
  l, r = line.split

  them =
    case l
    when "A" then 0
    when "B" then 1
    when "C" then 2
    end

  case r
  when "X"
    score += 0
    score += 1 + (them-1)%3
  when "Y"
    score += 3
    score += 1 + them
  when "Z"
    score += 6
    score += 1 + (them+1)%3
  end
end

puts score
