#!/usr/bin/env ruby
waypoint, position = 10+1i, 0

$stdin.each_line do |line|
  /(?<action>.)(?<n>.*)/ =~ line
  n = n.to_i
  case action
  when ?N then waypoint += n*1i
  when ?E then waypoint += n
  when ?S then waypoint += n*-1i
  when ?W then waypoint += -n
  when ?L then waypoint *= (1i)**(n/90)
  when ?R then waypoint *= (-1i)**(n/90)
  when ?F then position += n*waypoint
  end
end

p position.rect.map(&:abs).sum
