#!/usr/bin/env ruby
# using capture groups b/c it doesn't really matter and it's a lot easier to read
p $stdin
  .read
  .split("\n\n")
  .map { |doc| doc.split.sort.join ' ' }
  .grep(/^
    byr:(19[2-9][0-9]|200[0-2])\s
    (cid:\S*\s)?
    ecl:(amb|blu|brn|gry|grn|hzl|oth)\s
    eyr:(20(2[0-9]|30))\s
    hcl:\#[0-9a-f]{6}\s
    hgt:( (1([5-8][0-9]|9[0-3]))cm
        | (59|6[0-9]|7[0-6])in
        )\s
    iyr:(20(1[0-9]|20))\s
    pid:[0-9]{9}
  $/x)
  .size
