#!/usr/bin/env ruby
def num_orbits(orbits, planet)
  _, orbited = orbits.assoc planet
  return 0 unless orbited
  1 + num_orbits(orbits, orbited)
end

orbits = $stdin
  .readlines
  .map { |line| line.chomp.split ")" }
  .map(&:reverse)

puts orbits.map(&:first).sum { |planet|
  num_orbits orbits, planet
}
